execute @a ~0 ~-6 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-6 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-5 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-4 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-3 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-2 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~-1 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~0 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~1 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~2 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~3 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~4 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~5 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~6 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~7 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~8 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~9 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~0 ~10 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-10 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-9 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-8 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-7 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-6 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-5 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~-1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~0 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~1 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~2 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~3 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~4 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~5 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~6 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~7 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~8 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-4 ~10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-3 ~-10 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~
execute @a ~1 ~-3 ~-9 detect ~ ~ ~ leaves -1 particle fused:leaf ~ ~ ~